# -*- coding: utf-8 -*-
"""AIT 736_Final Project_Pooja-Zain-04-26-2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oXbyFtpUtRdzBARRuRCCCLp7lkt0zVEh

# Cost-Aware Credit Card Fraud Detection Using Machine Learning

**Author:** Pooja Shah and Zain Qadri

**Course:** AIT 736-003 Applied Machine Learning  

**Group:** 2

---

##  Problem Statement

Fraud detection is a **highly imbalanced classification problem**, where fraudulent transactions are very rare (~0.5%).  
Thus, **accuracy alone is misleading**.

We use a **business cost framework**:
- False Negative (missed fraud) = **$500 loss**
- False Positive (false alert) = **$10 cost**

---

##  Dataset

- Training Size: 1,296,675 transactions  
- Test Size: 555,719 transactions  
- Fraud Rate: ~0.58%
- https://www.kaggle.com/datasets/kartik2112/fraud-detection/data

---

##  Feature Engineering

We engineered **25+ features**:

###  Temporal Features
- Transaction hour, day, weekend
- Night transaction flag

###  Geospatial Features
- Distance: home → merchant
- Distance between transactions
- Travel speed (km/h)
- Impossible travel flag

###  Sequential Features
- Time gap between transactions
- Amount change from previous transaction

###  Risk Features
- Merchant risk
- Category risk

###  NLP Features (Lightweight)
- Merchant keyword risk
- Merchant name length & word count

---

##  Models Used

- Logistic Regression  
- Random Forest  
- Random Forest + SMOTE  
- XGBoost (final model)  

---

##  Final Results

| Model | Accuracy | Precision | Recall | F1 | Cost ($) |
|------|----------|-----------|--------|----|----------|
| **XGBoost ✓** | **0.9955** | **0.4586** | **0.9571** | **0.6201** | **70,240** |
| XGBoost + Rule Threshold | 0.9979 | 0.6690 | 0.9063 | 0.7697 | 110,120 |
| Random Forest | 0.9820 | 0.1675 | 0.9254 | 0.2837 | 178,660 |
| RF + SMOTE | 0.9916 | 0.2899 | 0.8154 | 0.4277 | 240,840 |
| Logistic Regression | 0.9520 | 0.0651 | 0.8559 | 0.1210 | 418,090 |

---

##  Model Performance

**PR-AUC:**
- XGBoost: 0.9301  
- RF: 0.7915  
- RF+SMOTE: 0.7099  
- LR: 0.2505  

**ROC-AUC:**
- XGBoost: 0.9984  
- RF: 0.9937  
- RF+SMOTE: 0.9810  
- LR: 0.9611  

---

##  Threshold Optimization

Best threshold (based on F1):

- τ = 0.90  
- Precision = 0.744  
- Recall = 0.888  
- F1 = 0.810  

---

##  Final Model Selection

**Selected Model: XGBoost (fixed threshold)**

- Lowest business cost  
- High fraud detection (recall ≈ 96%)  
- Best overall balance  

---

##  Key Insights

- Accuracy is not reliable for imbalanced data  
- XGBoost performs best across all metrics  
- SMOTE increases recall but also cost  
- High-value transactions are more risky  
- Fraud often involves abnormal location behavior  
- Geospatial + temporal features improve performance  
- Explainability increases trust  

---

##  Explainability

Example output:

> "Flagged due to high transaction amount, high-risk merchant, and rapid geographic change."

---

##  Conclusion

This project demonstrates that combining:

- Machine Learning  
- Feature Engineering  
- Cost-based Evaluation  
- Explainability  

leads to a **robust and practical fraud detection system**.

---

Step 0  Install packages
"""

!pip install -q xgboost imbalanced-learn

"""Step 1  Imports and setup"""

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    classification_report, confusion_matrix, ConfusionMatrixDisplay,
    precision_recall_curve, auc
)

from imblearn.over_sampling import SMOTE

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", lambda x: f"{x:,.4f}")

print("Setup complete.")

"""Step 2  Load data"""

train_df = pd.read_csv("/content/fraudTrain.csv")
test_df = pd.read_csv("/content/fraudTest.csv")

print("Train shape:", train_df.shape)
print("Test shape :", test_df.shape)

display(train_df.head())

"""Step 3  Basic cleaning"""

for df in [train_df, test_df]:
    if "Unnamed: 0" in df.columns:
        df.drop(columns=["Unnamed: 0"], inplace=True)

print("Cleaned shapes:")
print("Train:", train_df.shape)
print("Test :", test_df.shape)

print("Train columns:")
print(train_df.columns.tolist())

print("\nTrain info:")
train_df.info()

"""Step 4  Datetime conversion"""

for df in [train_df, test_df]:
    df["trans_date_trans_time"] = pd.to_datetime(df["trans_date_trans_time"])
    df["dob"] = pd.to_datetime(df["dob"])

print("Datetime conversion done.")

"""Step 5  Missing values and duplicates"""

print("Missing values in train:")
display(train_df.isnull().sum()[train_df.isnull().sum() > 0])

print("Missing values in test:")
display(test_df.isnull().sum()[test_df.isnull().sum() > 0])

print("Duplicate rows in train:", train_df.duplicated().sum())
print("Duplicate rows in test :", test_df.duplicated().sum())

"""Step 6  Target distribution"""

# ============================================
# CLASS DISTRIBUTION
# ============================================

import seaborn as sns
import matplotlib.pyplot as plt

# --------------------------------------------
# 1. Force correct type (VERY IMPORTANT)
# --------------------------------------------
train_df["is_fraud"] = train_df["is_fraud"].astype(str)   # <-- FIX

# --------------------------------------------
# 2. Print distribution
# --------------------------------------------
print("Class Counts:")
print(train_df["is_fraud"].value_counts())

print("\nClass Percentage:")
print(train_df["is_fraud"].value_counts(normalize=True) * 100)

# --------------------------------------------
# 3. Plot (MATCH palette with string keys)
# --------------------------------------------
plt.figure(figsize=(6,4))

ax = sns.countplot(
    x="is_fraud",
    data=train_df,
    palette={"0": "skyblue", "1": "red"}   # <-- FIX
)

# --------------------------------------------
# 4. Labels
# --------------------------------------------
plt.title("Class Distribution (Fraud vs Non-Fraud)")
plt.xlabel("Class (0 = Non-Fraud, 1 = Fraud)")
plt.ylabel("Count")

# --------------------------------------------
# 5. Add percentage labels
# --------------------------------------------
total = len(train_df)

for p in ax.patches:
    height = p.get_height()
    percent = 100 * height / total

    ax.text(
        p.get_x() + p.get_width()/2,
        height,
        f"{percent:.2f}%",
        ha="center",
        va="bottom",
        fontsize=10
    )

plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.tight_layout()
plt.show()

"""The dataset is highly imbalanced, with fraudulent transactions representing a very small proportion of the data. This imbalance makes accuracy unreliable and justifies the use of precision, recall, and F1-score.

Step 7  Core EDA features
"""

for df in [train_df, test_df]:
    df["trans_year"] = df["trans_date_trans_time"].dt.year
    df["trans_month"] = df["trans_date_trans_time"].dt.month
    df["trans_day"] = df["trans_date_trans_time"].dt.day
    df["trans_hour"] = df["trans_date_trans_time"].dt.hour
    df["trans_dayofweek"] = df["trans_date_trans_time"].dt.dayofweek
    df["trans_weekend"] = df["trans_dayofweek"].isin([5, 6]).astype(int)
    df["customer_age"] = df["trans_date_trans_time"].dt.year - df["dob"].dt.year

"""Step 8 - EDA visuals"""

# ============================================
# COLORED EDA VISUALIZATIONS
# ============================================

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Make plotting column string-safe
train_df["is_fraud"] = train_df["is_fraud"].astype(str)

# 1. Log Transaction Amount Distribution
plt.figure(figsize=(8,5))
plt.hist(
    np.log1p(train_df["amt"]),
    bins=50,
    color="royalblue",
    edgecolor="black",
    alpha=0.7
)
plt.title("Log Transaction Amount Distribution")
plt.xlabel("log(1 + amt)")
plt.ylabel("Frequency")
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.tight_layout()
plt.show()


# 2. Amount by Fraud Class
plt.figure(figsize=(8,5))
sns.boxplot(
    x="is_fraud",
    y="amt",
    data=train_df,
    palette={"0": "skyblue", "1": "red"}
)
plt.title("Transaction Amount by Fraud Class")
plt.xlabel("Class (0 = Non-Fraud, 1 = Fraud)")
plt.ylabel("Amount")
plt.grid(axis="y", linestyle="--", alpha=0.5)
plt.tight_layout()
plt.show()


# 3. Fraud Rate by Category
# Convert is_fraud back temporarily for mean calculation
train_df["is_fraud_num"] = train_df["is_fraud"].astype(int)

category_fraud = train_df.groupby("category")["is_fraud_num"].mean().sort_values(ascending=False)

plt.figure(figsize=(12,5))
category_fraud.plot(
    kind="bar",
    color="darkorange",
    edgecolor="black"
)
plt.title("Fraud Rate by Category")
plt.ylabel("Fraud Rate")
plt.xticks(rotation=45, ha="right")
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.tight_layout()
plt.show()


# 4. Fraud Rate by Hour
hour_fraud = train_df.groupby("trans_hour")["is_fraud_num"].mean()

plt.figure(figsize=(10,5))
plt.plot(
    hour_fraud.index,
    hour_fraud.values,
    marker="o",
    linewidth=2,
    color="purple"
)
plt.title("Fraud Rate by Hour")
plt.xlabel("Hour of Day")
plt.ylabel("Fraud Rate")
plt.grid(True, linestyle="--", alpha=0.6)
plt.tight_layout()
plt.show()

# Optional: convert target back to int for modeling
train_df["is_fraud"] = train_df["is_fraud"].astype(int)

"""1. The log-transformed distribution shows that most transactions occur at lower amounts, with a long tail of high-value transactions. This skewness suggests that extreme values may be important indicators of fraud.

2. Fraudulent transactions tend to have higher median values and greater variability compared to non-fraudulent ones, indicating that high-value transactions are more likely to be associated with fraud.

3. Certain transaction categories exhibit significantly higher fraud rates, suggesting that fraud risk is not uniformly distributed and depends on the type of transaction.

4. Fraudulent activity appears more frequent during late-night hours, indicating that time-based patterns can help identify suspicious transactions.
"""

#Fraud vs Non-Fraud Comparison
plt.figure(figsize=(8,5))
sns.histplot(data=train_df, x="amt", hue="is_fraud", bins=50, log_scale=True)
plt.title("Transaction Amount Distribution by Class")
plt.show()


#Day of Week Analysis
day_fraud = train_df.groupby("trans_dayofweek")["is_fraud"].mean()

plt.figure(figsize=(8,5))
day_fraud.plot(marker="o")
plt.title("Fraud Rate by Day of Week")
plt.ylabel("Fraud Rate")
plt.grid(True)
plt.show()


#Geospatial EDA
import numpy as np

def haversine_vectorized(lat1, lon1, lat2, lon2):
    R = 6371.0  # Earth radius in km

    lat1 = np.radians(lat1)
    lon1 = np.radians(lon1)
    lat2 = np.radians(lat2)
    lon2 = np.radians(lon2)

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = np.sin(dlat / 2.0) ** 2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2.0) ** 2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))

    return R * c

train_df["distance_home_merchant_km"] = haversine_vectorized(
    train_df["lat"],
    train_df["long"],
    train_df["merch_lat"],
    train_df["merch_long"]
)

test_df["distance_home_merchant_km"] = haversine_vectorized(
    test_df["lat"],
    test_df["long"],
    test_df["merch_lat"],
    test_df["merch_long"]
)

print("distance_home_merchant_km created successfully.")
plt.figure(figsize=(8,5))
sns.histplot(train_df["distance_home_merchant_km"], bins=50)
plt.title("Distance from Home Distribution")
plt.xlabel("Distance from Home to Merchant (km)")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x="is_fraud", y="distance_home_merchant_km", data=train_df)
plt.title("Distance from Home by Fraud Class")
plt.xlabel("Fraud")
plt.ylabel("Distance from Home to Merchant (km)")
plt.show()


#location intelligence
plt.figure(figsize=(8,5))
sns.boxplot(x="is_fraud", y="distance_home_merchant_km", data=train_df)
plt.title("Distance from Home by Fraud Class")
plt.show()



#speed/Movement
import numpy as np
import pandas as pd

def haversine_vectorized(lat1, lon1, lat2, lon2):
    R = 6371.0  # km

    lat1 = np.radians(lat1)
    lon1 = np.radians(lon1)
    lat2 = np.radians(lat2)
    lon2 = np.radians(lon2)

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = np.sin(dlat / 2.0) ** 2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2.0) ** 2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))

    return R * c

def add_sequential_features(df):
    df = df.sort_values(["cc_num", "unix_time"]).copy()

    # previous transaction info for same card
    df["prev_unix_time"] = df.groupby("cc_num")["unix_time"].shift(1)
    df["prev_merch_lat"] = df.groupby("cc_num")["merch_lat"].shift(1)
    df["prev_merch_long"] = df.groupby("cc_num")["merch_long"].shift(1)

    # time gap
    df["time_since_prev_txn_sec"] = df["unix_time"] - df["prev_unix_time"]
    df["time_since_prev_txn_sec"] = df["time_since_prev_txn_sec"].fillna(0)

    # distance from previous transaction
    df["distance_from_prev_txn_km"] = 0.0

    mask = df["prev_merch_lat"].notna() & df["prev_merch_long"].notna()

    df.loc[mask, "distance_from_prev_txn_km"] = haversine_vectorized(
        df.loc[mask, "prev_merch_lat"],
        df.loc[mask, "prev_merch_long"],
        df.loc[mask, "merch_lat"],
        df.loc[mask, "merch_long"]
    )

    # speed = distance / time
    df["speed_from_prev_kmph"] = 0.0
    valid_time = df["time_since_prev_txn_sec"] > 0

    df.loc[valid_time, "speed_from_prev_kmph"] = (
        df.loc[valid_time, "distance_from_prev_txn_km"] /
        (df.loc[valid_time, "time_since_prev_txn_sec"] / 3600.0)
    )

    # impossible travel flag
    df["impossible_travel_flag"] = (
        (df["distance_from_prev_txn_km"] > 500) &
        (df["time_since_prev_txn_sec"] > 0) &
        (df["time_since_prev_txn_sec"] < 3600)
    ).astype(int)

    # cleanup helper cols
    df.drop(columns=["prev_unix_time", "prev_merch_lat", "prev_merch_long"], inplace=True)

    return df

train_df = add_sequential_features(train_df)
test_df = add_sequential_features(test_df)

print("Sequential features created successfully.")
print(train_df[[
    "cc_num",
    "unix_time",
    "time_since_prev_txn_sec",
    "distance_from_prev_txn_km",
    "speed_from_prev_kmph",
    "impossible_travel_flag"
]].head())


plt.figure(figsize=(8,5))
sns.histplot(train_df["speed_from_prev_kmph"], bins=50)
plt.title("Speed Between Transactions")
plt.show()

"""**Distance from Home Distribution**

Most transactions occur relatively close to the customer’s home location, while a smaller number occur at larger distances. These larger-distance transactions may indicate unusual behavior and can be useful for fraud detection.

**Distance from Home by Fraud Class**

Fraudulent transactions tend to occur farther from the customer’s home location compared to legitimate ones, suggesting that geospatial distance is an informative risk signal

**Speed/Movement**

Most transactions occur at realistic movement speeds, while extreme values indicate unusual or impossible travel behavior. These abnormal movement patterns can serve as strong indicators of fraud.

1. Fraudulent transactions show a higher concentration in larger amounts compared to non-fraud transactions, reinforcing the importance of transaction value in fraud detection.

2. Fraud rates vary slightly across days of the week, suggesting that temporal patterns may contribute to identifying abnormal transaction behavior.

3. Most transactions occur close to the customer’s home location, while a smaller number occur at larger distances, which may indicate unusual or suspicious activity.

4. Fraudulent transactions tend to occur farther from the customer’s home location compared to legitimate ones, highlighting the importance of geospatial features in detecting fraud.

5. Most transactions occur at realistic travel speeds, while extreme values indicate unrealistic movement patterns, which can be strong indicators of fraudulent activity.

Step 9  Merchant and category risk features
"""

merchant_risk = train_df.groupby("merchant")["is_fraud"].mean()
category_risk = train_df.groupby("category")["is_fraud"].mean()

train_df["merchant_risk"] = train_df["merchant"].map(merchant_risk)
test_df["merchant_risk"] = test_df["merchant"].map(merchant_risk)

train_df["category_risk"] = train_df["category"].map(category_risk)
test_df["category_risk"] = test_df["category"].map(category_risk)

train_df["merchant_risk"] = train_df["merchant_risk"].fillna(train_df["merchant_risk"].mean())
test_df["merchant_risk"] = test_df["merchant_risk"].fillna(train_df["merchant_risk"].mean())

train_df["category_risk"] = train_df["category_risk"].fillna(train_df["category_risk"].mean())
test_df["category_risk"] = test_df["category_risk"].fillna(train_df["category_risk"].mean())

"""Step 10  Transaction count features"""

cust_count = train_df.groupby("cc_num")["cc_num"].count()
merchant_count = train_df.groupby("merchant")["merchant"].count()

train_df["cust_trans_count"] = train_df["cc_num"].map(cust_count)
test_df["cust_trans_count"] = test_df["cc_num"].map(cust_count).fillna(0)

train_df["merchant_trans_count"] = train_df["merchant"].map(merchant_count)
test_df["merchant_trans_count"] = test_df["merchant"].map(merchant_count).fillna(0)

"""Step 11  Distance from home to merchant"""

def haversine(lat1, lon1, lat2, lon2):
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat / 2) ** 2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2) ** 2
    c = 2 * np.arcsin(np.sqrt(a))
    return 6371 * c

train_df["distance_home_merchant_km"] = haversine(
    train_df["lat"], train_df["long"],
    train_df["merch_lat"], train_df["merch_long"]
)

test_df["distance_home_merchant_km"] = haversine(
    test_df["lat"], test_df["long"],
    test_df["merch_lat"], test_df["merch_long"]
)

"""Step 12  Strong new feature: previous transaction behavior"""

def add_sequential_features(df):
    df = df.sort_values(["cc_num", "trans_date_trans_time"]).copy()

    df["prev_unix_time"] = df.groupby("cc_num")["unix_time"].shift(1)
    df["prev_merch_lat"] = df.groupby("cc_num")["merch_lat"].shift(1)
    df["prev_merch_long"] = df.groupby("cc_num")["merch_long"].shift(1)
    df["prev_amt"] = df.groupby("cc_num")["amt"].shift(1)

    df["time_since_prev_txn_sec"] = df["unix_time"] - df["prev_unix_time"]
    df["time_since_prev_txn_sec"] = df["time_since_prev_txn_sec"].fillna(-1)

    df["distance_from_prev_txn_km"] = 0.0
    valid_prev = df["prev_merch_lat"].notna() & df["prev_merch_long"].notna()

    df.loc[valid_prev, "distance_from_prev_txn_km"] = haversine(
        df.loc[valid_prev, "prev_merch_lat"],
        df.loc[valid_prev, "prev_merch_long"],
        df.loc[valid_prev, "merch_lat"],
        df.loc[valid_prev, "merch_long"]
    )

    df["speed_from_prev_kmph"] = 0.0
    valid_time = df["time_since_prev_txn_sec"] > 0

    df.loc[valid_time, "speed_from_prev_kmph"] = (
        df.loc[valid_time, "distance_from_prev_txn_km"] /
        (df.loc[valid_time, "time_since_prev_txn_sec"] / 3600.0)
    )

    df["impossible_travel_flag"] = (
        (df["distance_from_prev_txn_km"] > 500) &
        (df["time_since_prev_txn_sec"] > 0) &
        (df["time_since_prev_txn_sec"] < 3600)
    ).astype(int)

    df["amt_change_from_prev"] = df["amt"] - df["prev_amt"]
    df["amt_change_from_prev"] = df["amt_change_from_prev"].fillna(0)

    df.drop(
        columns=["prev_unix_time", "prev_merch_lat", "prev_merch_long", "prev_amt"],
        inplace=True
    )

    return df

train_df = add_sequential_features(train_df)
test_df = add_sequential_features(test_df)

# ============================================
# RULE-BASED MERCHANT TEXT FEATURES
# ============================================

import re
import numpy as np

# --------------------------------------------
# 1. Clean merchant text
# --------------------------------------------
def clean_text(x):
    x = str(x).lower()
    x = re.sub(r"[^a-z0-9\s]", " ", x)
    x = re.sub(r"\s+", " ", x).strip()
    return x

train_df["merchant_clean"] = train_df["merchant"].apply(clean_text)
test_df["merchant_clean"] = test_df["merchant"].apply(clean_text)


# --------------------------------------------
# 2. Keyword-based merchant risk feature
# --------------------------------------------
suspicious_words = [
    "shop", "store", "travel", "jewel", "luxury",
    "transfer", "electronics", "wire", "gift",
    "cash", "market"
]

def merchant_nlp_risk(name):
    name = str(name).lower()
    return sum(1 for word in suspicious_words if word in name)

train_df["merchant_nlp_risk"] = train_df["merchant_clean"].apply(merchant_nlp_risk)
test_df["merchant_nlp_risk"] = test_df["merchant_clean"].apply(merchant_nlp_risk)


# --------------------------------------------
# 3. Extra text-based features
# --------------------------------------------
train_df["merchant_name_length"] = train_df["merchant_clean"].apply(len)
test_df["merchant_name_length"] = test_df["merchant_clean"].apply(len)

train_df["merchant_word_count"] = train_df["merchant_clean"].apply(lambda x: len(x.split()))
test_df["merchant_word_count"] = test_df["merchant_clean"].apply(lambda x: len(x.split()))


# --------------------------------------------
# 4. Preview
# --------------------------------------------
display(train_df[[
    "merchant",
    "merchant_clean",
    "merchant_nlp_risk",
    "merchant_name_length",
    "merchant_word_count"
]].head())

"""Step 13  Additional useful features"""

for df in [train_df, test_df]:
    df["amt_log"] = np.log1p(df["amt"])
    df["city_pop_log"] = np.log1p(df["city_pop"])
    df["high_amt_flag"] = (df["amt"] > train_df["amt"].quantile(0.95)).astype(int)
    df["night_transaction"] = df["trans_hour"].isin([0,1,2,3,4]).astype(int)
    df["weekend_night"] = ((df["trans_weekend"] == 1) & (df["night_transaction"] == 1)).astype(int)

print(train_df.columns)

FEATURES = [

    # -------------------------
    # Transaction
    # -------------------------
    "amt",
    "amt_log",
    "high_amt_flag",

    # -------------------------
    # Time
    # -------------------------
    "trans_hour",
    "trans_dayofweek",
    "trans_weekend",
    "trans_month",
    "night_transaction",
    "weekend_night",

    # -------------------------
    # Customer
    # -------------------------
    "customer_age",

    # -------------------------
    # Location
    # -------------------------
    "distance_home_merchant_km",
    "city_pop_log",

    # -------------------------
    # Sequential behavior
    # -------------------------
    "time_since_prev_txn_sec",
    "distance_from_prev_txn_km",
    "speed_from_prev_kmph",
    "impossible_travel_flag",
    "amt_change_from_prev",

    # -------------------------
    # Risk encoding
    # -------------------------
    "merchant_risk",
    "category_risk",

    # -------------------------
    # Count features
    # -------------------------
    "cust_trans_count",
    "merchant_trans_count",

    # -------------------------
    # NLP features (NEW)
    # -------------------------
    "merchant_nlp_risk",
    "merchant_name_length",
    "merchant_word_count"
]

TARGET = "is_fraud"

# ============================================
# FINAL DATA CHECK
# ============================================

# Create model matrices
X_train = train_df[FEATURES].copy()
y_train = train_df[TARGET].copy()

X_test = test_df[FEATURES].copy()
y_test = test_df[TARGET].copy()

# --------------------------------------------
# Check shapes
# --------------------------------------------
print("Final X_train shape:", X_train.shape)
print("Final X_test shape :", X_test.shape)

# --------------------------------------------
# Check for object (non-numeric) columns
# --------------------------------------------
obj_cols = X_train.select_dtypes(include=["object"]).columns.tolist()
print("Object columns left:", obj_cols)

# --------------------------------------------
# Check for missing values
# --------------------------------------------
print("\nMissing values in X_train:")
print(X_train.isnull().sum().sum())

print("\nMissing values in X_test:")
print(X_test.isnull().sum().sum())

# --------------------------------------------
# Optional: preview
# --------------------------------------------
display(X_train.head())

"""Step 14  Age groups"""

def age_group(age):
    if age < 25:
        return 0   # Young
    elif age < 45:
        return 1   # Adult
    elif age < 65:
        return 2   # Middle
    else:
        return 3   # Senior

train_df["age_group_encoded"] = train_df["customer_age"].apply(age_group)
test_df["age_group_encoded"] = test_df["customer_age"].apply(age_group)

"""Step 15  Logistic Regression baseline"""

# ============================================
#  LOGISTIC REGRESSION BASELINE + CV
# ============================================

from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.pipeline import Pipeline

# Cross-validation pipeline to avoid scaling leakage
cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

lr_pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    ))
])

lr_cv_f1 = cross_val_score(
    lr_pipe,
    X_train,
    y_train,
    cv=cv,
    scoring="f1",
    n_jobs=-1
)

print("===== Logistic Regression Cross-Validation =====")
print("CV F1 Scores:", lr_cv_f1)
print("Mean CV F1  :", lr_cv_f1.mean())


# Final test evaluation
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

log_reg = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

log_reg.fit(X_train_scaled, y_train)

y_pred_log = log_reg.predict(X_test_scaled)

print("\n===== Logistic Regression Test Results =====")
print("Accuracy   :", accuracy_score(y_test, y_pred_log))
print("Precision  :", precision_score(y_test, y_pred_log, zero_division=0))
print("Recall     :", recall_score(y_test, y_pred_log, zero_division=0))
print("F1 Binary  :", f1_score(y_test, y_pred_log, zero_division=0))
print("F1 Micro   :", f1_score(y_test, y_pred_log, average="micro"))
print("F1 Macro   :", f1_score(y_test, y_pred_log, average="macro"))

"""Step 16 Random Forest"""

# ============================================
# RANDOM FOREST + CV
# ============================================

from sklearn.model_selection import StratifiedKFold, cross_val_score

cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

rf_cv_model = RandomForestClassifier(
    n_estimators=50,
    max_depth=8,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf_cv_f1 = cross_val_score(
    rf_cv_model,
    X_train,
    y_train,
    cv=cv,
    scoring="f1",
    n_jobs=-1
)

print("===== Random Forest Cross-Validation =====")
print("CV F1 Scores:", rf_cv_f1)
print("Mean CV F1  :", rf_cv_f1.mean())


# Final test model
rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=8,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

print("\n===== Random Forest Test Results =====")
print("Accuracy   :", accuracy_score(y_test, y_pred_rf))
print("Precision  :", precision_score(y_test, y_pred_rf, zero_division=0))
print("Recall     :", recall_score(y_test, y_pred_rf, zero_division=0))
print("F1 Binary  :", f1_score(y_test, y_pred_rf, zero_division=0))
print("F1 Micro   :", f1_score(y_test, y_pred_rf, average="micro"))
print("F1 Macro   :", f1_score(y_test, y_pred_rf, average="macro"))

print("RF fitted. Number of trees:", len(rf_model.estimators_))

"""Step 17 SMOTE experiment"""

# ============================================
# RANDOM FOREST + SMOTE + CV
# ============================================

from sklearn.model_selection import StratifiedKFold, cross_val_score
from imblearn.pipeline import Pipeline as ImbPipeline

cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

# Leakage-safe CV: SMOTE happens inside each fold only
rf_smote_pipe = ImbPipeline([
    ("smote", SMOTE(sampling_strategy=0.20, random_state=42)),
    ("model", RandomForestClassifier(
        n_estimators=20,
        max_depth=8,
        random_state=42,
        n_jobs=-1
    ))
])

rf_smote_cv_f1 = cross_val_score(
    rf_smote_pipe,
    X_train,
    y_train,
    cv=cv,
    scoring="f1",
    n_jobs=-1
)

print("===== Random Forest + SMOTE Cross-Validation =====")
print("CV F1 Scores:", rf_smote_cv_f1)
print("Mean CV F1  :", rf_smote_cv_f1.mean())


# Final test model
smote = SMOTE(sampling_strategy=0.20, random_state=42)

X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)

rf_smote = RandomForestClassifier(
    n_estimators=20,
    max_depth=8,
    random_state=42,
    n_jobs=-1
)

rf_smote.fit(X_train_sm, y_train_sm)

y_pred_smote = rf_smote.predict(X_test)

print("\n===== Random Forest + SMOTE Test Results =====")
print("Accuracy   :", accuracy_score(y_test, y_pred_smote))
print("Precision  :", precision_score(y_test, y_pred_smote, zero_division=0))
print("Recall     :", recall_score(y_test, y_pred_smote, zero_division=0))
print("F1 Binary  :", f1_score(y_test, y_pred_smote, zero_division=0))
print("F1 Micro   :", f1_score(y_test, y_pred_smote, average="micro"))
print("F1 Macro   :", f1_score(y_test, y_pred_smote, average="macro"))

print("RF + SMOTE fitted. Number of trees:", len(rf_smote.estimators_))

"""SMOTE was applied to address class imbalance by generating synthetic fraud samples in the training data.

To prevent data leakage, SMOTE was applied within each cross-validation fold using a pipeline.

Although SMOTE improved recall, it increased false positives, leading to higher business cost. Therefore, it was used as a comparative experiment rather than the final model.

Step 18 XGBoost
"""

# ============================================
#  XGBOOST HYPERPARAMETER TUNING
# ============================================

from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()
scale_pos_weight = neg / pos

xgb_base = XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    n_jobs=-1
)

param_dist = {
    "n_estimators": [100, 150, 200],
    "max_depth": [3, 4, 5, 6],
    "learning_rate": [0.03, 0.05, 0.08, 0.10],
    "subsample": [0.7, 0.8, 0.9],
    "colsample_bytree": [0.7, 0.8, 0.9],
    "min_child_weight": [1, 3, 5],
    "gamma": [0, 0.1, 0.3],
    "reg_lambda": [1, 3, 5]
}

cv = StratifiedKFold(
    n_splits=3,
    shuffle=True,
    random_state=42
)

xgb_search = RandomizedSearchCV(
    estimator=xgb_base,
    param_distributions=param_dist,
    n_iter=10,          # 10 is enough and faster for Colab
    scoring="f1",
    cv=cv,
    verbose=1,
    random_state=42,
    n_jobs=-1
)

xgb_search.fit(X_train, y_train)

print("Best Parameters:")
print(xgb_search.best_params_)

print("\nBest CV F1 Score:")
print(xgb_search.best_score_)

"""### XGBoost Hyperparameter Tuning

RandomizedSearchCV was used to tune the XGBoost model because full grid search would be computationally expensive on the large fraud dataset. The tuning process optimized F1-score using stratified cross-validation to preserve the fraud/non-fraud class distribution. The best parameters were then used to train the final XGBoost model.
"""

# ============================================
#  FINAL TUNED XGBOOST MODEL
# ============================================

xgb_model = xgb_search.best_estimator_

y_pred_xgb = xgb_model.predict(X_test)
y_prob_xgb = xgb_model.predict_proba(X_test)[:, 1]

print("===== Tuned XGBoost =====")
print("Accuracy   :", accuracy_score(y_test, y_pred_xgb))
print("Precision  :", precision_score(y_test, y_pred_xgb, zero_division=0))
print("Recall     :", recall_score(y_test, y_pred_xgb, zero_division=0))
print("F1 Binary  :", f1_score(y_test, y_pred_xgb, zero_division=0))
print("F1 Micro   :", f1_score(y_test, y_pred_xgb, average="micro"))
print("F1 Macro   :", f1_score(y_test, y_pred_xgb, average="macro"))

"""Step 22 — Comparison table"""

# ============================================
# STEP 22: MODEL COMPARISON TABLE (FINAL)
# ============================================

results = pd.DataFrame([
    {
        "Model": "Logistic Regression",
        "Accuracy": accuracy_score(y_test, y_pred_log),
        "Precision": precision_score(y_test, y_pred_log, zero_division=0),
        "Recall": recall_score(y_test, y_pred_log, zero_division=0),
        "F1 Binary": f1_score(y_test, y_pred_log, zero_division=0)
    },
    {
        "Model": "Random Forest",
        "Accuracy": accuracy_score(y_test, y_pred_rf),
        "Precision": precision_score(y_test, y_pred_rf, zero_division=0),
        "Recall": recall_score(y_test, y_pred_rf, zero_division=0),
        "F1 Binary": f1_score(y_test, y_pred_rf, zero_division=0)
    },
    {
        "Model": "Random Forest + SMOTE",
        "Accuracy": accuracy_score(y_test, y_pred_smote),
        "Precision": precision_score(y_test, y_pred_smote, zero_division=0),
        "Recall": recall_score(y_test, y_pred_smote, zero_division=0),
        "F1 Binary": f1_score(y_test, y_pred_smote, zero_division=0)
    },
    {
        "Model": "XGBoost",
        "Accuracy": accuracy_score(y_test, y_pred_xgb),
        "Precision": precision_score(y_test, y_pred_xgb, zero_division=0),
        "Recall": recall_score(y_test, y_pred_xgb, zero_division=0),
        "F1 Binary": f1_score(y_test, y_pred_xgb, zero_division=0)
    }
])

metric_cols = ["Accuracy", "Precision", "Recall", "F1 Binary"]
results[metric_cols] = results[metric_cols].round(4)

results_f1 = results.sort_values(by="F1 Binary", ascending=False)
display(results_f1)

best_f1_model = results_f1.iloc[0]["Model"]
print(f"\nBest Model based on F1 Binary: {best_f1_model}")

"""Step 19 Confusion matrices"""

# ============================================
# CONFUSION MATRICES
# ============================================

fig, axes = plt.subplots(2, 4, figsize=(24,10))

models = [
    ("Logistic Regression", y_pred_log, "Blues"),
    ("Random Forest", y_pred_rf, "Greens"),
    ("RF + SMOTE", y_pred_smote, "Oranges"),
    ("XGBoost", y_pred_xgb, "Purples")
]

# Row 1 → Counts
for i, (name, y_pred, cmap) in enumerate(models):
    ConfusionMatrixDisplay.from_predictions(
        y_test,
        y_pred,
        ax=axes[0, i],
        cmap=cmap,
        colorbar=False
    )
    axes[0, i].set_title(f"{name} (Counts)")
    axes[0, i].set_xlabel("Predicted")
    axes[0, i].set_ylabel("Actual")

# Row 2 → Normalized
for i, (name, y_pred, cmap) in enumerate(models):
    ConfusionMatrixDisplay.from_predictions(
        y_test,
        y_pred,
        ax=axes[1, i],
        cmap=cmap,
        normalize="true",
        colorbar=False
    )
    axes[1, i].set_title(f"{name} (Normalized)")
    axes[1, i].set_xlabel("Predicted")
    axes[1, i].set_ylabel("Actual")

plt.tight_layout()
plt.show()

"""Step 20 Precision-Recall curve"""

# ============================================
#  COMBINED PRECISION-RECALL CURVE
# ============================================

# Predicted probabilities
y_prob_log = log_reg.predict_proba(X_test_scaled)[:, 1]
y_prob_rf = rf_model.predict_proba(X_test)[:, 1]
y_prob_smote = rf_smote.predict_proba(X_test)[:, 1]
y_prob_xgb = xgb_model.predict_proba(X_test)[:, 1]

model_probs = {
    "Logistic Regression": y_prob_log,
    "Random Forest": y_prob_rf,
    "RF + SMOTE": y_prob_smote,
    "XGBoost": y_prob_xgb
}

plt.figure(figsize=(9,6))

pr_auc_results = []

colors = ["blue", "green", "orange", "purple"]

for (model_name, y_prob), color in zip(model_probs.items(), colors):
    precision_curve, recall_curve, _ = precision_recall_curve(y_test, y_prob)
    pr_auc = auc(recall_curve, precision_curve)

    pr_auc_results.append({
        "Model": model_name,
        "PR AUC": pr_auc
    })

    plt.plot(
        recall_curve,
        precision_curve,
        label=f"{model_name} (AUC={pr_auc:.4f})",
        linewidth=2,
        color=color
    )

# baseline (random classifier)
baseline = sum(y_test) / len(y_test)
plt.hlines(baseline, 0, 1, linestyles="dashed", colors="gray", label="Baseline")

plt.xlabel("Recall", fontsize=12)
plt.ylabel("Precision", fontsize=12)
plt.title("Precision-Recall Curve (All Models)", fontsize=14)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.xlim([0,1])
plt.ylim([0,1])
plt.show()

# Table
pr_auc_df = pd.DataFrame(pr_auc_results).sort_values(by="PR AUC", ascending=False)
display(pr_auc_df)

"""XGBoost significantly outperforms all models with PR AUC of 0.9303, demonstrating strong precision-recall tradeoff. Random Forest performs reasonably well, while SMOTE does not improve performance. Logistic Regression fails to capture complex fraud patterns."""

# ============================================
#  COMBINED ROC-AUC CURVE
# ============================================

from sklearn.metrics import roc_curve, roc_auc_score

# Predicted probabilities
y_prob_log = log_reg.predict_proba(X_test_scaled)[:, 1]
y_prob_rf = rf_model.predict_proba(X_test)[:, 1]
y_prob_smote = rf_smote.predict_proba(X_test)[:, 1]
y_prob_xgb = xgb_model.predict_proba(X_test)[:, 1]

model_probs = {
    "Logistic Regression": y_prob_log,
    "Random Forest": y_prob_rf,
    "RF + SMOTE": y_prob_smote,
    "XGBoost": y_prob_xgb
}

plt.figure(figsize=(9,6))

roc_auc_results = []

for model_name, y_prob in model_probs.items():
    fpr, tpr, _ = roc_curve(y_test, y_prob)
    roc_auc = roc_auc_score(y_test, y_prob)

    roc_auc_results.append({
        "Model": model_name,
        "ROC AUC": roc_auc
    })

    plt.plot(
        fpr,
        tpr,
        linewidth=2,
        label=f"{model_name} (AUC={roc_auc:.4f})"
    )

# random classifier baseline
plt.plot([0, 1], [0, 1], linestyle="--", label="Random Baseline")

plt.xlabel("False Positive Rate", fontsize=12)
plt.ylabel("True Positive Rate / Recall", fontsize=12)
plt.title("ROC-AUC Curve (All Models)", fontsize=14)
plt.legend()
plt.grid(True)
plt.show()

roc_auc_df = pd.DataFrame(roc_auc_results).sort_values(by="ROC AUC", ascending=False)
display(roc_auc_df)

"""Although ROC-AUC values are very high for all models, ROC curves can be overly optimistic for imbalanced datasets. Therefore, Precision-Recall AUC is considered a more reliable metric for fraud detection performance.

### Threshold Tuning Insight

Threshold tuning demonstrates the trade-off between precision and recall.
Although an optimal threshold can improve F1-score, the final model selection
is based on business cost, where XGBoost with the default threshold provided
the lowest overall cost.

** Model Explainability **

To improve interpretability, we implemented a rule-based explanation layer that highlights key factors contributing to fraud predictions.

These explanations combine:
- Transaction amount
- Merchant and category risk
- Time-based behavior
- Geospatial movement patterns

This approach helps analysts understand why a transaction was flagged, making the model more transparent and easier to trust in real-world applications.
"""

# ============================================
#  FEATURE IMPORTANCE (RANDOM FOREST)
# ============================================

rf_importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": rf_model.feature_importances_
}).sort_values(by="Importance", ascending=False)

# Show top 15
display(rf_importance.head(15))


# Plot top 10
plt.figure(figsize=(10,6))

top_features = rf_importance.head(10)

bars = plt.barh(
    top_features["Feature"][::-1],
    top_features["Importance"][::-1]
)

# Add value labels (VERY GOOD FOR PRESENTATION)
for bar in bars:
    plt.text(
        bar.get_width(),
        bar.get_y() + bar.get_height()/2,
        f"{bar.get_width():.3f}",
        va='center',
        fontsize=9
    )

plt.xlabel("Importance")
plt.title("Top 10 Feature Importance - Random Forest")
plt.grid(axis="x")
plt.tight_layout()
plt.show()

# ============================================
# XGBOOST + RULE-BASED RISK THRESHOLD
# ============================================
# ============================================
# COST FUNCTION
# ============================================

cost_fn = 500
cost_fp = 10

def compute_cost(y_true, y_pred, model_name):
    TN, FP, FN, TP = confusion_matrix(y_true, y_pred).ravel()
    total_cost = FN * cost_fn + FP * cost_fp

    return {
        "Model": model_name,
        "False Positives": FP,
        "False Negatives": FN,
        "Total Cost ($)": total_cost
    }
# Vectorized (faster than apply)
amt = X_test["amt"].values

dynamic_thresholds = np.where(
    amt >= 5000, 0.50,
    np.where(
        amt >= 1000, 0.60,
        np.where(
            amt >= 100, 0.75, 0.90
        )
    )
)

y_pred_risk_threshold = (y_prob_xgb >= dynamic_thresholds).astype(int)

print("===== XGBoost + Rule-Based Risk Threshold =====")
print("Accuracy   :", accuracy_score(y_test, y_pred_risk_threshold))
print("Precision  :", precision_score(y_test, y_pred_risk_threshold, zero_division=0))
print("Recall     :", recall_score(y_test, y_pred_risk_threshold, zero_division=0))
print("F1 Binary  :", f1_score(y_test, y_pred_risk_threshold, zero_division=0))
print("F1 Micro   :", f1_score(y_test, y_pred_risk_threshold, average="micro"))
print("F1 Macro   :", f1_score(y_test, y_pred_risk_threshold, average="macro"))

# Cost comparison
cost_risk_threshold = pd.DataFrame([
    compute_cost(y_test, y_pred_risk_threshold, "XGBoost + Rule-Based Risk Threshold")
])

display(cost_risk_threshold)

"""Step 22 BAYES MINIMUM RISK (BMR)"""

# ============================================
# BMR-INSPIRED DYNAMIC THRESHOLD + SENSITIVITY
# ============================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, ConfusionMatrixDisplay
)

# --------------------------------------------------
# 1. Cost assumptions
# --------------------------------------------------
C_FP = 50.0     # Cost of one false positive alert
C_FN = 500.0    # Cost of missing one fraud case


# --------------------------------------------------
# 2. BMR-inspired threshold function
# --------------------------------------------------
def bmr_threshold(amt, c_fp=C_FP):
    """
    BMR-inspired dynamic threshold.
    Higher transaction amount -> lower threshold.
    """
    return np.clip(
        c_fp / (c_fp + np.maximum(amt, 0.01)),
        0.01,
        0.99
    )


# --------------------------------------------------
# 3. Visualize threshold behavior
# --------------------------------------------------
amounts = np.logspace(0, 4, 300)  # $1 to $10,000
thresholds = bmr_threshold(amounts)

plt.figure(figsize=(9, 4))
plt.semilogx(amounts, thresholds, linewidth=2)
plt.axhline(0.5, color="gray", linestyle="--", label="Fixed 0.5 threshold")

example_amounts = np.array([5, 500, 5000])
plt.scatter(
    example_amounts,
    bmr_threshold(example_amounts),
    zorder=5,
    color="red",
    label="Example amounts"
)

for amt in example_amounts:
    t = float(bmr_threshold(np.array([amt])))
    plt.annotate(
        f"${amt}\nτ={t:.2f}",
        xy=(amt, t),
        xytext=(amt * 1.5, t + 0.05),
        fontsize=9
    )

plt.xlabel("Transaction Amount ($, log scale)")
plt.ylabel("Minimum Fraud Probability Threshold (τ)")
plt.title(f"BMR-Inspired Dynamic Threshold (C_FP = ${C_FP:.0f})")
plt.legend()
plt.tight_layout()
plt.show()


# --------------------------------------------------
# 4. Apply BMR threshold to XGBoost probabilities
# --------------------------------------------------
if "y_prob_xgb" not in globals() or "X_test" not in globals():
    raise RuntimeError("Run the XGBoost section first to populate y_prob_xgb and X_test.")

test_amounts = X_test["amt"].values
tau_per_tx = bmr_threshold(test_amounts, c_fp=C_FP)

y_pred_bmr = (y_prob_xgb >= tau_per_tx).astype(int)


# --------------------------------------------------
# 5. Evaluate BMR predictions
# --------------------------------------------------
print("===== XGBoost + BMR-Inspired Dynamic Threshold =====")
print("Accuracy   :", accuracy_score(y_test, y_pred_bmr))
print("Precision  :", precision_score(y_test, y_pred_bmr, zero_division=0))
print("Recall     :", recall_score(y_test, y_pred_bmr, zero_division=0))
print("F1 Binary  :", f1_score(y_test, y_pred_bmr, zero_division=0))
print("F1 Macro   :", f1_score(y_test, y_pred_bmr, average="macro"))

cm_bmr = confusion_matrix(y_test, y_pred_bmr)
TN_b, FP_b, FN_b, TP_b = cm_bmr.ravel()

cost_bmr = FN_b * C_FN + FP_b * C_FP

print(f"\nBusiness cost FN×${C_FN:.0f} + FP×${C_FP:.0f} = ${cost_bmr:,.0f}")
print(f"False Positives: {FP_b}")
print(f"False Negatives: {FN_b}")

ConfusionMatrixDisplay.from_predictions(
    y_test,
    y_pred_bmr,
    cmap="Purples",
    colorbar=False
)
plt.title("XGBoost + BMR-Inspired Dynamic Threshold")
plt.tight_layout()
plt.show()


# --------------------------------------------------
# 6. Compare fixed-threshold XGBoost vs BMR
# --------------------------------------------------
cm_xgb_fixed = confusion_matrix(y_test, y_pred_xgb)
TN_x, FP_x, FN_x, TP_x = cm_xgb_fixed.ravel()

cost_xgb_fixed = FN_x * C_FN + FP_x * C_FP

comparison = pd.DataFrame([
    {
        "Approach": "XGBoost Fixed Threshold",
        "Precision": precision_score(y_test, y_pred_xgb, zero_division=0),
        "Recall": recall_score(y_test, y_pred_xgb, zero_division=0),
        "F1 Binary": f1_score(y_test, y_pred_xgb, zero_division=0),
        "False Positives": FP_x,
        "False Negatives": FN_x,
        "Business Cost ($)": cost_xgb_fixed
    },
    {
        "Approach": "XGBoost + BMR-Inspired Dynamic Threshold",
        "Precision": precision_score(y_test, y_pred_bmr, zero_division=0),
        "Recall": recall_score(y_test, y_pred_bmr, zero_division=0),
        "F1 Binary": f1_score(y_test, y_pred_bmr, zero_division=0),
        "False Positives": FP_b,
        "False Negatives": FN_b,
        "Business Cost ($)": cost_bmr
    }
])

display(comparison.sort_values(by="Business Cost ($)"))


# --------------------------------------------------
# 7. Sensitivity analysis for C_FP
# --------------------------------------------------
cfp_values = [5, 10, 25, 50, 75, 100, 150, 200]
bmr_sensitivity_results = []

for c_fp in cfp_values:
    tau_temp = bmr_threshold(test_amounts, c_fp=c_fp)
    y_pred_temp = (y_prob_xgb >= tau_temp).astype(int)

    TN, FP, FN, TP = confusion_matrix(y_test, y_pred_temp).ravel()
    total_cost = FN * C_FN + FP * c_fp

    bmr_sensitivity_results.append({
        "C_FP": c_fp,
        "Precision": precision_score(y_test, y_pred_temp, zero_division=0),
        "Recall": recall_score(y_test, y_pred_temp, zero_division=0),
        "F1 Binary": f1_score(y_test, y_pred_temp, zero_division=0),
        "False Positives": FP,
        "False Negatives": FN,
        "Total Cost ($)": total_cost
    })

bmr_sensitivity_df = pd.DataFrame(bmr_sensitivity_results)
bmr_sensitivity_df = bmr_sensitivity_df.sort_values(by="Total Cost ($)")

display(bmr_sensitivity_df)

plt.figure(figsize=(8, 5))
plt.plot(
    bmr_sensitivity_df["C_FP"],
    bmr_sensitivity_df["Total Cost ($)"],
    marker="o"
)
plt.xlabel("False Positive Cost (C_FP)")
plt.ylabel("Total Business Cost ($)")
plt.title("BMR Sensitivity Analysis: Effect of C_FP")
plt.grid(True)
plt.tight_layout()
plt.show()

print("Best BMR setting based on total cost:")
display(bmr_sensitivity_df.iloc[[0]])

"""### BMR-Inspired Dynamic Threshold and Sensitivity Analysis

A BMR-inspired dynamic threshold was tested to make fraud decisions more cost-sensitive. The threshold decreases for higher transaction amounts, meaning high-value transactions are flagged with lower required fraud probability.

Because the false-positive cost is an assumption, a sensitivity analysis was performed across multiple \(C_{FP}\) values. This helps evaluate how precision, recall, false positives, false negatives, and total business cost change under different operational cost assumptions.

The final model selection is based on the lowest total business cost, not only F1-score or accuracy.

A rule-based explanation layer was implemented to provide human-understandable reasoning for model predictions. This enhances transparency and helps analysts interpret fraud signals in real-world applications.”
"""

# ============================================
# FRAUD EXPLANATION
# ============================================

# --------------------------------------------
# 1. Rule-based explanation function
# --------------------------------------------
def explain_transaction_fast(row):
    reasons = []

    # Amount-based risk
    if row.get("high_amt_flag", 0) == 1:
        reasons.append("high transaction amount")

    # Location / movement risk
    if row.get("distance_home_merchant_km", 0) > 100:
        reasons.append("transaction far from customer's usual location")

    rapid_geo_change = False
    if row.get("distance_from_prev_txn_km", 0) > 50:
        rapid_geo_change = True

    if row.get("time_since_prev_txn_sec", 0) < 10000 and row.get("distance_from_prev_txn_km", 0) > 50:
        rapid_geo_change = True

    if rapid_geo_change:
        reasons.append("rapid geographic change between transactions")

    if row.get("impossible_travel_flag", 0) == 1:
        dist = row.get("distance_from_prev_txn_km", 0)
        time_gap = row.get("time_since_prev_txn_sec", 0)
        reasons.append(f"impossible travel: {dist:.0f} km in {time_gap/3600:.2f} hrs")

    if row.get("speed_from_prev_kmph", 0) > 900:
        reasons.append("unrealistic travel speed")

    # Merchant / category risk
    if row.get("merchant_risk", 0) > train_df["merchant_risk"].quantile(0.90):
        reasons.append("high-risk merchant")

    if row.get("category_risk", 0) > train_df["category_risk"].quantile(0.90):
        reasons.append("high-risk category")

    # Time-based risk
    if row.get("night_transaction", 0) == 1:
        reasons.append("night-time transaction")

    if row.get("weekend_night", 0) == 1:
        reasons.append("weekend night activity")

    # Keep explanation concise
    reasons = reasons[:4]

    if len(reasons) == 0:
        return "Flagged due to combined risk signals."

    return "Flagged due to: " + ", ".join(reasons) + "."

# --------------------------------------------
# 2. Select sample transactions
# --------------------------------------------
prob_series = pd.Series(y_prob_xgb, index=y_test.index)
pred_xgb_series = pd.Series(y_pred_xgb, index=y_test.index)

# True Positives
tp_idx = y_test[(pred_xgb_series == 1) & (y_test == 1)].index[:3]

# False Positive
fp_idx = y_test[(pred_xgb_series == 1) & (y_test == 0)].index[:1]

# Highest probability case
top_idx = prob_series.nlargest(1).index

sample_indices = list(tp_idx) + list(fp_idx) + list(top_idx)
sample_indices = list(dict.fromkeys(sample_indices))  # remove duplicates

print("Selected indices:", sample_indices)

# --------------------------------------------
# 3. Generate explanations
# --------------------------------------------
explanations = []

for idx in sample_indices:
    row = X_test.loc[idx]
    prob = float(prob_series.loc[idx])
    pred_label = int(pred_xgb_series.loc[idx])
    actual_label = int(y_test.loc[idx])

    explanation = explain_transaction_fast(row)

    if actual_label == 1 and pred_label == 1:
        case_type = "True Positive"
    elif actual_label == 0 and pred_label == 1:
        case_type = "False Positive"
    elif actual_label == 1 and pred_label == 0:
        case_type = "False Negative"
    else:
        case_type = "True Negative"

    explanations.append({
        "index": idx,
        "case_type": case_type,
        "amount": round(float(row.get("amt", 0)), 2),
        "fraud_prob": round(prob, 4),
        "actual_label": actual_label,
        "predicted_label": pred_label,
        "explanation": explanation
    })

    print("\n" + "=" * 80)
    print(f"Transaction index : {idx}")
    print(f"Case Type         : {case_type}")
    print(f"Amount            : ${float(row.get('amt', 0)):.2f}")
    print(f"Fraud probability : {prob:.4f}")
    print(f"Actual label      : {actual_label}")
    print(f"Predicted label   : {pred_label}")

    print("\nExplanation:")
    print(explanation)

## --------------------------------------------
# 4. Display explanation table
# --------------------------------------------
explanation_df = pd.DataFrame(explanations)

explanation_df = explanation_df.rename(columns={
    "index": "Transaction ID",
    "case_type": "Case Type",
    "amount": "Amount ($)",
    "fraud_prob": "Fraud Probability",
    "actual_label": "Actual Label",
    "predicted_label": "Predicted Label",
    "explanation": "Explanation"
})

display(explanation_df)

# ============================================
# TRANSACTION DIAGNOSTIC TOOL (ROBUST)
# ============================================

def diagnose_transaction(idx):
    if idx not in X_test.index:
        print(f" Index {idx} not found in X_test")
        return

    row = X_test.loc[idx]

    print("\n===== Transaction Diagnostics =====")
    print(f"Transaction ID         : {idx}")
    print(f"Distance from home     : {row.get('distance_home_merchant_km', 0):.2f} km")
    print(f"Distance from previous : {row.get('distance_from_prev_txn_km', 0):.2f} km")
    print(f"Time gap              : {row.get('time_since_prev_txn_sec', 0):.2f} sec")
    print(f"Speed                : {row.get('speed_from_prev_kmph', 0):.2f} km/h")
    print(f"Impossible travel     : {int(row.get('impossible_travel_flag', 0))}")

    print("\n--- Risk Signals ---")

    if row.get("impossible_travel_flag", 0) == 1:
        print(" STRONG: Impossible travel detected")

    if row.get("speed_from_prev_kmph", 0) > 900:
        print(" STRONG: Unrealistic travel speed")

    if row.get("distance_from_prev_txn_km", 0) > 50:
        print(" MODERATE: Large geographic movement")

    if row.get("distance_home_merchant_km", 0) > 100:
        print(" MODERATE: Far from home location")

    if row.get("high_amt_flag", 0) == 1:
        print(" MODERATE: High transaction amount")

    print("\n------------------------------")


# Example call
diagnose_transaction(253809)

"""Selected transaction cases were analyzed using the explanation framework to demonstrate how the model identifies fraud patterns. The results show that flagged transactions exhibit strong behavioral and geospatial anomalies.”"""

# ============================================
# FINAL EXPLANATION TABLE
# ============================================

explanation_df = pd.DataFrame(explanations)

# Rename columns for readability
explanation_df = explanation_df.rename(columns={
    "index": "Transaction ID",
    "case_type": "Case Type",
    "amount": "Amount ($)",
    "fraud_prob": "Fraud Probability",
    "actual_label": "Actual",
    "predicted_label": "Predicted",
    "explanation": "Explanation"
})

# Sort by probability (high risk first)
explanation_df = explanation_df.sort_values(by="Fraud Probability", ascending=False)

# Round values
explanation_df["Fraud Probability"] = explanation_df["Fraud Probability"].round(4)

# Map labels to human-readable format (VERY IMPORTANT)
label_map = {0: "Non-Fraud", 1: "Fraud"}
explanation_df["Actual"] = explanation_df["Actual"].map(label_map)
explanation_df["Predicted"] = explanation_df["Predicted"].map(label_map)

# Optional: reorder columns for cleaner view
explanation_df = explanation_df[
    ["Transaction ID", "Case Type", "Amount ($)", "Fraud Probability",
     "Actual", "Predicted", "Explanation"]
]

display(explanation_df)

"""Step 23 Cost-based evaluation

### Cost-Based Evaluation

Because missed fraud cases are more expensive than false alerts, a cost-based evaluation was used in addition to standard metrics. A false negative was assigned a cost of $500, while a false positive was assigned a cost of $10. The model with the lowest total cost is considered the most practical model for deployment.
"""

# ============================================
#  COST-BASED MODEL COMPARISON
# ============================================

cost_fn = 500   # Cost of missing a fraud transaction (False Negative)
cost_fp = 10    # Cost of false alert / investigation (False Positive)

def compute_cost(y_true, y_pred, model_name):
    cm = confusion_matrix(y_true, y_pred)
    TN, FP, FN, TP = cm.ravel()

    total_cost = FN * cost_fn + FP * cost_fp

    return {
        "Model": model_name,
        "False Positives": FP,
        "False Negatives": FN,
        "Total Cost ($)": total_cost
    }

cost_df = pd.DataFrame([
    compute_cost(y_test, y_pred_log, "Logistic Regression"),
    compute_cost(y_test, y_pred_rf, "Random Forest"),
    compute_cost(y_test, y_pred_smote, "Random Forest + SMOTE"),
    compute_cost(y_test, y_pred_xgb, "XGBoost")
])

cost_df = cost_df.sort_values(by="Total Cost ($)")

display(cost_df)

best_model = cost_df.iloc[0]["Model"]
print(f"\nBest Model based on Business Cost: {best_model}")

"""Step 24 Simple explainability examples

Inspection of predicted fraud cases shows that transactions flagged by the model typically exhibit high values in key features such as transaction amount, merchant risk, and abnormal geospatial movement, validating the model’s learned patterns.

Step 25: Fraud Case Analysis

The analysis of predicted fraud cases shows that the model relies heavily on key features such as transaction amount, merchant risk, and behavioral patterns. Many flagged transactions exhibit high-risk characteristics such as large transaction amounts or unusual patterns.

This confirms that the model is capturing meaningful fraud signals rather than random noise.
"""

# ============================================
# TOP FEATURES + FRAUD CASE ANALYSIS
# ============================================

# Top features from RF
top_features = rf_importance["Feature"].head(5).tolist()
print("Top important features:", top_features)


# Select predicted fraud cases
fraud_examples = X_test[y_pred_rf == 1].copy()

# Add actual labels
fraud_examples["Actual Label"] = y_test.loc[fraud_examples.index]

# Convert labels to readable format
label_map = {0: "Non-Fraud", 1: "Fraud"}
fraud_examples["Actual Label"] = fraud_examples["Actual Label"].map(label_map)

# Select useful columns (avoid duplicates)
cols_to_show = list(dict.fromkeys(top_features + ["amt", "Actual Label"]))

fraud_examples = fraud_examples[cols_to_show]

# Sort by amount (optional → better insight)
fraud_examples = fraud_examples.sort_values(by="amt", ascending=False)

# Display sample
display(fraud_examples.head(5))


print("\nFraud prediction distribution:")
print(fraud_examples["Actual Label"].value_counts())

"""Step 25 Rule-based explanation helper"""

# ============================================
#  FRAUD EXPLANATION (ALIGNED WITH XGBOOST)
# ============================================

def explain_transaction(row):
    reasons = []

    if row.get("high_amt_flag", 0) == 1:
        reasons.append("high transaction amount")

    if row.get("merchant_risk", 0) > train_df["merchant_risk"].quantile(0.90):
        reasons.append("high-risk merchant")

    if row.get("category_risk", 0) > train_df["category_risk"].quantile(0.90):
        reasons.append("high-risk category")

    if row.get("night_transaction", 0) == 1:
        reasons.append("night-time transaction")

    if row.get("impossible_travel_flag", 0) == 1:
        reasons.append("impossible travel pattern")

    if row.get("speed_from_prev_kmph", 0) > 900:
        reasons.append("unrealistic travel speed")

    if len(reasons) == 0:
        return "Flagged due to combined risk signals."
    else:
        return "Flagged due to: " + ", ".join(reasons) + "."


# Use FINAL model (XGBoost, not RF)
sample_flagged = X_test[y_pred_xgb == 1].head(10).copy()

sample_flagged["Actual Label"] = y_test.loc[sample_flagged.index]
sample_flagged["Explanation"] = sample_flagged.apply(explain_transaction, axis=1)

display(sample_flagged[[
    "amt",
    "merchant_risk",
    "category_risk",
    "distance_home_merchant_km",
    "time_since_prev_txn_sec",
    "distance_from_prev_txn_km",
    "speed_from_prev_kmph",
    "impossible_travel_flag",
    "Actual Label",
    "Explanation"
]])

"""Step 26 Final comparison including risk-based threshold"""

# ============================================
# FINAL MODEL SUMMARY TABLE
# ============================================

final_results = pd.DataFrame([
    {
        "Model": "Logistic Regression",
        "F1 Binary": f1_score(y_test, y_pred_log, zero_division=0),
        "Recall": recall_score(y_test, y_pred_log, zero_division=0),
        "Precision": precision_score(y_test, y_pred_log, zero_division=0),
        "Total Cost ($)": compute_cost(y_test, y_pred_log, "Logistic Regression")["Total Cost ($)"]
    },
    {
        "Model": "Random Forest",
        "F1 Binary": f1_score(y_test, y_pred_rf, zero_division=0),
        "Recall": recall_score(y_test, y_pred_rf, zero_division=0),
        "Precision": precision_score(y_test, y_pred_rf, zero_division=0),
        "Total Cost ($)": compute_cost(y_test, y_pred_rf, "Random Forest")["Total Cost ($)"]
    },
    {
        "Model": "Random Forest + SMOTE",
        "F1 Binary": f1_score(y_test, y_pred_smote, zero_division=0),
        "Recall": recall_score(y_test, y_pred_smote, zero_division=0),
        "Precision": precision_score(y_test, y_pred_smote, zero_division=0),
        "Total Cost ($)": compute_cost(y_test, y_pred_smote, "Random Forest + SMOTE")["Total Cost ($)"]
    },
    {
        "Model": "XGBoost",
        "F1 Binary": f1_score(y_test, y_pred_xgb, zero_division=0),
        "Recall": recall_score(y_test, y_pred_xgb, zero_division=0),
        "Precision": precision_score(y_test, y_pred_xgb, zero_division=0),
        "Total Cost ($)": compute_cost(y_test, y_pred_xgb, "XGBoost")["Total Cost ($)"]
    },
    {
        "Model": "XGBoost + Rule-Based Risk Threshold",
        "F1 Binary": f1_score(y_test, y_pred_risk_threshold, zero_division=0),
        "Recall": recall_score(y_test, y_pred_risk_threshold, zero_division=0),
        "Precision": precision_score(y_test, y_pred_risk_threshold, zero_division=0),
        "Total Cost ($)": compute_cost(y_test, y_pred_risk_threshold, "XGBoost + Rule-Based Risk Threshold")["Total Cost ($)"]
    },
        {
        "Model": "XGBoost + BMR-Inspired Dynamic Threshold",
        "F1 Binary": f1_score(y_test, y_pred_bmr, zero_division=0),
        "Recall": recall_score(y_test, y_pred_bmr, zero_division=0),
        "Precision": precision_score(y_test, y_pred_bmr, zero_division=0),
        "Total Cost ($)": compute_cost(y_test, y_pred_bmr, "XGBoost + BMR-Inspired Dynamic Threshold")["Total Cost ($)"]
    }
])

final_results = final_results.sort_values(by="Total Cost ($)")
display(final_results)

# ============================================
# PHASE X: SIMPLE NLP FEATURES FROM MERCHANT
# ============================================

import re
import numpy as np

# --------------------------------------------
# 1. Clean merchant text
# --------------------------------------------
def clean_text(x):
    x = str(x).lower()
    x = re.sub(r"[^a-z0-9\s]", " ", x)
    x = re.sub(r"\s+", " ", x).strip()
    return x

train_df["merchant_clean"] = train_df["merchant"].apply(clean_text)
test_df["merchant_clean"] = test_df["merchant"].apply(clean_text)


# --------------------------------------------
# 2. Keyword-based risk feature (improved)
# --------------------------------------------
suspicious_words = [
    "shop", "store", "travel", "jewel", "luxury",
    "transfer", "electronics", "wire", "gift",
    "cash", "market"
]

def merchant_nlp_risk(name):
    name = str(name).lower()
    return sum(1 for word in suspicious_words if word in name)

train_df["merchant_nlp_risk"] = train_df["merchant_clean"].apply(merchant_nlp_risk)
test_df["merchant_nlp_risk"] = test_df["merchant_clean"].apply(merchant_nlp_risk)


# --------------------------------------------
# 3. Extra lightweight text features
# --------------------------------------------
train_df["merchant_name_length"] = train_df["merchant_clean"].apply(len)
test_df["merchant_name_length"] = test_df["merchant_clean"].apply(len)

train_df["merchant_word_count"] = train_df["merchant_clean"].apply(lambda x: len(x.split()))
test_df["merchant_word_count"] = test_df["merchant_clean"].apply(lambda x: len(x.split()))


# --------------------------------------------
# 4. Preview
# --------------------------------------------
display(train_df[[
    "merchant",
    "merchant_clean",
    "merchant_nlp_risk",
    "merchant_name_length",
    "merchant_word_count"
]].head())

"""#  Final Model Comparison & Business Evaluation

The final model comparison based on performance metrics and business cost shows that **XGBoost with a fixed threshold achieves the lowest total business cost**, making it the most effective model for fraud detection in this study.

---

## 🔍 Model-wise Insights

### XGBoost (Best Model)
XGBoost provides the best overall balance between fraud detection performance and business cost.  
It achieves high recall while keeping false positives at a manageable level, making it the final selected model.

---

### XGBoost + Rule-Based Risk Threshold
The rule-based risk threshold improves precision and F1-score, but it reduces recall and increases total business cost.  
Therefore, it is useful as an experiment but not selected as the final model.

---

### Random Forest
Random Forest achieves high recall but low precision, which leads to many false positives and higher business cost.

---

### Random Forest + SMOTE
SMOTE improves class balance during training, but it does not improve practical test performance or business cost.

---

### Logistic Regression
Logistic Regression serves as an interpretable baseline but performs worse than tree-based models because it cannot capture complex fraud patterns as effectively.

---

## Final Conclusion

Based on business cost minimization, **XGBoost with a fixed threshold is selected as the final model**.  
It provides the best trade-off between fraud detection recall, precision, and operational cost.

---

## Key Takeaway

> XGBoost achieves the lowest business cost and best overall practical performance, making it the final selected model.

#  Key Findings

1. Fraud detection is a highly imbalanced classification problem; therefore, accuracy alone is not a reliable metric.
2. Tree-based models such as Random Forest and XGBoost outperform Logistic Regression on fraud-specific metrics like recall and F1-score.
3. SMOTE improves class balance during training but does not necessarily improve real-world performance and may increase business cost.
4. Sequential geospatial-temporal features (e.g., time gap, travel distance, speed, and impossible travel) significantly enhance model realism and predictive power.
5. Cost-based evaluation provides a more practical and business-relevant assessment than accuracy alone.
6. Risk-based and dynamic thresholding introduce a business-aware decision layer, but require careful tuning to avoid excessive false positives.
7. Model explainability improves transparency and trust by providing interpretable reasons for flagged transactions.

---

#  Conclusion

This study presents an end-to-end fraud detection system using supervised machine learning on a highly imbalanced financial transaction dataset.

Among the evaluated models, Random Forest and XGBoost consistently outperformed Logistic Regression in recall and F1-score, which are critical metrics for fraud detection. Although SMOTE improved class balance, it did not reduce overall business cost, highlighting that synthetic data balancing does not always translate into practical benefits.

A key contribution of this work is the integration of cost-based evaluation. By incorporating the financial impact of false negatives and false positives, the model selection process becomes more aligned with real-world business objectives. While the Bayes Minimum Risk (BMR)-inspired approach provides a theoretically sound framework for dynamic thresholding, it resulted in higher overall cost compared to a fixed-threshold XGBoost model in this case.

The model was further strengthened by incorporating behavioral and geospatial features, such as transaction timing, location shifts, and travel patterns, which effectively capture real-world fraud behavior.

Additionally, an explainability layer was implemented to generate human-readable reasons for flagged transactions, improving model transparency and usability.

Overall, this project demonstrates that combining machine learning, domain knowledge, cost-sensitive evaluation, and interpretability leads to a robust and practical fraud detection system.

---

#  Interpretation of Results

The experimental results provide several key insights:

- Accuracy is not a reliable metric in imbalanced classification problems such as fraud detection.
- Random Forest and XGBoost achieved higher recall, making them more effective at identifying fraudulent transactions.
- SMOTE improved recall but increased false positives, leading to higher overall business cost.
- Threshold tuning highlights the trade-off between precision and recall, emphasizing the importance of selecting an appropriate decision boundary.
- Cost-sensitive approaches, including BMR-inspired thresholding, introduce dynamic decision-making but must be validated against actual business cost.
- Geospatial and temporal features significantly improve predictive performance by capturing abnormal transaction patterns.

Overall, the findings emphasize that cost-sensitive evaluation and domain-specific feature engineering are essential for building practical and deployable fraud detection systems.

An AI-style explanation layer was explored to generate natural language explanations. However, a rule-based approach was selected due to its transparency, consistency, and efficiency.
"""

import glob
from google.colab import files

# Install nbconvert
!pip install -q nbconvert

notebooks = glob.glob("/content/AIT_736_Final_Project_Pooja_Zain_04_26_2026.ipynb")

if len(notebooks) == 0:
    print("No .ipynb file found in /content")
else:
    notebook_name = notebooks[0]
    print("Converting:", notebook_name)
    !jupyter nbconvert --to html "$notebook_name"

    html_file = notebook_name.replace(".ipynb", ".html")
    files.download(html_file)